FROM node:18-alpine As development

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:18-alpine As production

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install --only=production

COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/package.json ./
COPY --from=builder /usr/src/app/.env.local ./
# Копируем папку database
COPY --from=builder /usr/src/app/src/database ./src/database
# Копируем миграции
COPY --from=builder /usr/src/app/src/migrations ./src/migrations

EXPOSE 3000

CMD ["node", "dist/main"]