services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: smart-resume-ai-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - ./nginx/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - smart-resume-ai-net
    restart: unless-stopped

  smart-resume-ai-api:
    build:                       # собираем локально
      context: .
      dockerfile: Dockerfile.prod
    container_name: smart-resume-ai-api
    env_file:
      - .env.local                # берёт все секреты и ключи
    environment:                 # только то, чего нет в .env
      NODE_ENV: production
      VIRTUAL_HOST: smartresume-ai.com
      VIRTUAL_PORT: 3000
      LETSENCRYPT_HOST: smartresume-ai.com
      LETSENCRYPT_EMAIL: resumecopilotai@gmail.com
    networks:
      - smart-resume-ai-net
    depends_on:
      - smart-resume-ai-pg       # ждём Postgres
    restart: unless-stopped

  smart-resume-ai-pg:
    image: postgres:15
    container_name: smart-resume-ai-pg
    env_file:
      - .env.local              # POSTGRES_* переменные берутся отсюда
    volumes:
      - smart-resume-ai-postgres-data:/var/lib/postgresql/data
      - ./backups:/backups
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $${POSTGRES_USER:-postgres}" ]
      interval: 2s
      timeout: 5s
      retries: 10
    networks:
      - smart-resume-ai-net
    restart: unless-stopped
    command: postgres -c 'max_connections=200'

volumes:
  postgres-data:

networks:
  smart-resume-ai-net:
    driver: bridge
